// Js for the index page
function text(){
    alert("please wait...")
}
function sign(){
    alert("please wait...")
}

function topOne(){
    alert("Welcome Home")
}
function topTwo(){
    alert("please wait...")
}
function topThree(){
    alert("please wait...")
}

function topFour(){
    alert("Tel:0701-000-000")
}
function but(){
    alert("More info on the service section")
}
function sect(){
    alert("More for less? Visit our service link.")
}